### ISSUE TITLE
Internal webserver has failed to start

### ISSUE THREAD

**Issue by DejFidOFF** [BillyGalbreath/VS-LiveMap#2]
15.6.2024 14:45:03 [Error] [LiveMap] Internal webserver has failed to start
15.6.2024 14:45:03 [Error] [LiveMap] System.Net.HttpListenerException (5): Acess denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at livemap.httpd.WebServer.<RunAsyncInfiniteLoop>b__10_0(Object _) in /var/lib/jenkins/workspace/VS-LiveMap/src/httpd/WebServer.cs:line 57

**Comment by BillyGalbreath** [comment]
https://vs.pl3x.net/livemap-access-denied
